spring:
  application:
    name: tutorial
server:
  port: 8080
management:
  endpoints:
    enabled-by-default: True
---
spring:
  profiles: dev
  application:
    name: tutorial
server:
  port: 9090

---
spring:
  profiles: prod
  application:
    name: tutorial
server:
  port: 4431